# Generated by Django 2.2.2 on 2019-06-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20190613_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
