# Generated by Django 2.2.2 on 2019-06-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
