# Generated by Django 2.2.2 on 2019-06-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Prodcts',
        ),
    ]
