# Generated by Django 2.2.2 on 2019-06-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_auto_20190613_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodcts',
        ),
    ]
