# Generated by Django 2.2.2 on 2019-06-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_productmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
